name: Events
description: Plugin for moderating events
version: 1.5.0dev(5)
author: Rabbit_Hunter13
main: com.rabbit13.events.main.Main
api-version: "1.13"
softdepend:
  - "Multiverse-Core"
  - "Multiworld"
  - "WorldEdit"
commands:
  event:
    description: "command for moderating events and creating eventplaces"
    usage: "/events help"
    aliases:
      - e